### ISSUE TITLE
Bug: sentiment-rnn-minibatch.py - Passing 'words' instead of 'sentences' causes a type error in the embedding layer

### ISSUE THREAD

**Issue by DrawingProcess** [ldi-kyunghee/AI3003-nn4nlp#1]
Description:
In the training loop of sentiment-rnn-minibatch.py, the model is currently being passed the 'words' variable instead of the 'sentences' tensor. This leads to the following error during embedding lookup:
```
TypeError: embedding(): argument 'indices' (position 2) must be Tensor, not int...
```

Problematic Code:
```python
logits = model(words)
```

Solution:
```python
logits = model(sentences)
```

**Comment by mjeensung** [comment]
Thanks for reporting the issue, @DrawingProcess! I've fixed it in a10588fb433e241df66bb1a6f41559a7431caab4.
